[tool.poetry]
name = "PROJECT_NAME"
version = "0.1.1"
description = ""
authors = ["Dawson Booth <github@dawsonbooth.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/dawsonbooth/PROJECT_NAME"
repository = "https://github.com/dawsonbooth/PROJECT_NAME"
keywords = []
classifiers = [
    "Environment :: Console",
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
include = [
    "LICENSE",
]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]
pytest = "^6.2.1"
rope = "^0.18.0"
pyinstaller = "^4.2"
macholib = { version = "^1.8", markers = "sys_platform == 'darwin'" }
pefile = { version = "^2017.8.1", markers = "sys_platform == 'win32'" }
pywin32-ctypes = { version = "^0.2.0", markers = "sys_platform == 'win32'" }
pyclean = "^2.0.0"
invoke = "^1.4.1"
mypy = "^0.790"
black = "^20.8b1"
flake8 = "^3.8.4"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
