name: Release

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - "v*" # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  Release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Set up Poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install
      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          poetry run inv release

  Linux:
    runs-on: ubuntu-latest
    needs: [Release]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Set up Poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install
      - name: Build project
        run: |
          poetry run inv build
      - name: Upload release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          poetry run inv upload

  MacOS:
    runs-on: macos-latest
    needs: [Release]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Set up Poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install
      - name: Build project
        run: |
          poetry run inv build
      - name: Upload release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          poetry run inv upload

  Windows:
    runs-on: windows-latest
    needs: [Release]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Set up Poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install
      - name: Build project
        run: |
          poetry run inv build
      - name: Upload release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          poetry run inv upload
